package i18n

var catalogues = map[Language]map[Key]string{
	English: english,
	French:  french,
	Spanish: spanish,
	German:  german,
}

var english = map[Key]string{
	Library: "Library", Tracks: "Tracks", Queue: "Queue", NowPlaying: "Now Playing",
	Stopped: "Stopped", Playing: "Playing", Paused: "Paused", NothingPlaying: "Nothing playing", UnknownArtist: "Unknown artist",
	EmptyLibrary: "No library.\nPress r to scan.", NoLibraryMatches: "No library matches.\nPress Esc to clear the filter.", LibraryEmpty: "Library is empty.\nPress r to scan again.",
	EmptyScope: "This scope has no tracks.\nChoose another Library entry.", EmptyAlbum: "No tracks in %s / %s.\nChoose another Library entry.", EmptyArtist: "No tracks by %s.\nChoose another Library entry.",
	NoTrackMatches: "No tracks match %q.\nPress Esc to clear the filter.", NoMusicFound: "No music found.\nCheck music_dir, then press r to rescan.", EmptyQueue: "Queue is empty.\nPlay a track from Tracks.",
	TerminalTooSmall: "galdr needs at least %dx%d — you have %dx%d", SearchPlaceholder: "search…", ResultsOne: "%d/%d result", ResultsOther: "%d/%d results",
	UnavailableOne: "%d unavailable", UnavailableOther: "%d unavailable", DurationsProgress: "Durations %d/%d", DurationsSummaryOne: "Durations %d/%d · %d unavailable", DurationsSummaryOther: "Durations %d/%d · %d unavailable",
	Volume: "Vol", Mute: "Mute", Shuffle: "Shuffle", Repeat: "Repeat", On: "on", Off: "off", All: "all", One: "one", ErrorPrefix: "error:",
	ScopeAll: "Scope: all tracks", ScopeNamed: "Scope: %s", FilterContext: "%s  ·  Filter: %q (%d/%d)", FilterBadge: "[filter: %s %d/%d]", MuteBadge: "[mute]", ShuffleBadge: "[shuffle]", RepeatBadge: "[repeat: %s]", QueueSelected: "sel", QueueNow: "now",
	Playlists: "Playlists", PlaylistEmpty: "No saved playlists.", PlaylistHint: "j/k move  enter load  S save queue", PlaylistSaveTitle: "Save current queue", PlaylistNamePlaceholder: "playlist name", PlaylistOverwrite: "Replace %q?", PlaylistOverwriteHint: "y replace · n refuse · Esc cancel", PlaylistSaveHint: "Enter save · Esc cancel", PlaylistTracksTitle: "Playlist: %s", PlaylistTracksEmpty: "This playlist has no available tracks.", PlaylistSkippedOne: "%d entry ignored", PlaylistSkippedOther: "%d entries ignored", PlaylistAddNew: "＋ New playlist", PlaylistAddChooseHint: "Enter add · Esc cancel", PlaylistAddTitle: "New playlist:", PlaylistAddHint: "Enter create and add · Esc back", PlaylistAddExists: "Playlist already exists; select it from the list",
	StatusLibraryScanFailed: "Library scan failed", StatusLoadedOne: "Loaded %d track", StatusLoadedOther: "Loaded %d tracks", StatusRescanFailed: "Rescan failed", StatusRescannedOne: "Rescanned: %d track", StatusRescannedOther: "Rescanned: %d tracks",
	StatusScopeAll: "Scope: all tracks", StatusScopeEmpty: "Scope: %s/%s (empty)", StatusScopeAlbum: "Scope: %s/%s", StatusScopeArtist: "Scope: %s", StatusMovedUp: "Moved up", StatusMovedDown: "Moved down", StatusRemovedQueue: "Removed from queue", StatusQueueCleared: "Queue cleared", StatusFilterCleared: "Filter cleared", StatusFilter: "Filter: %s (%d/%d)", StatusVolume: "Volume: %d%%", StatusNoVisibleTracks: "No visible tracks to play", StatusStopped: "Stopped", StatusEndQueue: "End of queue", StatusFailedAdvance: "Failed to advance", StatusPlaying: "Playing: %s", StatusShuffleOn: "Shuffle on", StatusShuffleOff: "Shuffle off", StatusRepeatAll: "Repeat: all", StatusRepeatOne: "Repeat: one", StatusRepeatOff: "Repeat: off", StatusMuted: "Muted", StatusUnmuted: "Unmuted (%d%%)", StatusMutedVolume: "Muted (volume: %d%%)", StatusFailedLoad: "Failed to load track", StatusFailedStart: "Failed to start playback", StatusFailedPrepare: "Failed to prepare next track", StatusFailedDecode: "Failed to decode track", StatusFailedStop: "Failed to stop playback", StatusPaused: "Paused", StatusResumed: "Resumed",
	StatusAddedQueue: "Added to queue: %s", StatusPlayNext: "Playing next: %s", StatusPlaylistListFailed: "Could not list playlists", StatusPlaylistSaveFailed: "Could not save playlist", StatusPlaylistInvalidName: "Invalid playlist name", StatusPlaylistLoadFailed: "Could not load playlist", StatusPlaylistEmptyQueue: "Queue is empty", StatusPlaylistSaved: "Saved %s (%d tracks)", StatusPlaylistLoaded: "Loaded %s (%d tracks)", StatusPlaylistLoadedSkipped: "Loaded %s (%d tracks, %d skipped)", StatusPlaylistTrackAdded: "Added %s to %s", StatusPlaylistTracksAdded: "Added %d tracks to %s", StatusPlaylistCreatedWithTrack: "Created %s and added %s", StatusPlaylistCreatedWithTracks: "Created %s with %d tracks", StatusPlaylistDestinationMissing: "Playlist is no longer available", StatusPlaylistTrackMissing: "Track is no longer in the playlist", StatusPlaylistTrackRemoved: "Removed %s from %s", StatusPlaylistWriteFailed: "Could not update playlist",
	ShortcutLibrary: "j/k move  h/l close/open  enter select  A add to playlist  r rescan", ShortcutPlaylists: "j/k move  enter load  S save", ShortcutTracks: "j/k move  enter play  a add  A add to playlist  N play next", ShortcutPlaylistTracks: "j/k move  enter play  a add  A add to playlist  N play next  d remove", ShortcutQueue: "j/k move  K/J reorder  d remove  c clear  enter play", ShortcutGlobal: "tab focus  [/] source  P playlists  / search  ? help  q quit",
	HelpTitle: "Keybindings", HelpNavigation: "Navigation", HelpPlayback: "Playback", HelpLibrarySearch: "Library and search", HelpQueue: "Queue", HelpApplication: "Application",
	HelpNavMove: "j / k, ↑ / ↓    move selection", HelpNavOpen: "h / l, ← / →    seek or open / close", HelpNavPanel: "tab / shift+tab  next / previous panel", HelpNavChoose: "1 / 2 / 3        Library / Tracks / Queue", HelpNavSelect: "enter            select or play", HelpNavSeek: "home / end       seek to start / end", HelpPlayPause: "space            play / pause", HelpStop: "x                stop", HelpNextPrev: "n / p            next / previous", HelpVolume: "+ / -            volume up / down", HelpMute: "m                mute", HelpShuffleRepeat: "s / R            shuffle / repeat", HelpRescan: "r                rescan library", HelpSearch: "/                search", HelpClearFilter: "Esc / C-l        close / clear filter", HelpQueueUp: "K / shift+↑      move item up", HelpQueueDown: "J / shift+↓      move item down", HelpQueueRemove: "d / c            remove / clear", HelpQueueAdd: "a                add selected track", HelpPlayNext: "N                play selected next", HelpAddPlaylist: "A                add track, artist or album to a playlist", HelpPlaylistRemove: "d                remove selected playlist occurrence", HelpPlaylists: "P                open playlists", HelpClose: "? / esc          close help", HelpQuit: "q / ctrl+c       quit",
	DiagLoadConfig: "load config", DiagInitAudio: "initialize audio", DiagLoadState: "could not load state:", DiagDurationUnavailable: "duration probing unavailable:", DiagMPRISLost: "MPRIS connection lost:", DiagMPRISUnavailable: "MPRIS unavailable:", DiagMPRISStop: "could not stop MPRIS:", DiagTUI: "tui", DiagSaveState: "could not save state:",
}

var french = translated(english, map[Key]string{
	Library: "Bibliothèque", Tracks: "Pistes", Queue: "File d’attente", NowPlaying: "Lecture en cours", Stopped: "Arrêté", Playing: "Lecture", Paused: "En pause", NothingPlaying: "Aucune lecture", UnknownArtist: "Artiste inconnu",
	Playlists: "Playlists", PlaylistEmpty: "Aucune playlist enregistrée.", PlaylistHint: "j/k déplacer  entrée charger  S enregistrer", PlaylistSaveTitle: "Enregistrer la file actuelle", PlaylistNamePlaceholder: "nom de la playlist", PlaylistOverwrite: "Remplacer %q ?", PlaylistOverwriteHint: "y remplacer · n refuser · Échap annuler", PlaylistSaveHint: "Entrée enregistrer · Échap annuler", PlaylistTracksTitle: "Playlist : %s", PlaylistTracksEmpty: "Cette playlist ne contient aucune piste disponible.", PlaylistSkippedOne: "%d entrée ignorée", PlaylistSkippedOther: "%d entrées ignorées", PlaylistAddNew: "＋ Nouvelle playlist", PlaylistAddChooseHint: "Entrée ajouter · Échap annuler", PlaylistAddTitle: "Nouvelle playlist :", PlaylistAddHint: "Entrée créer et ajouter · Échap retour", PlaylistAddExists: "Cette playlist existe déjà ; sélectionnez-la dans la liste",
	EmptyLibrary: "Aucune bibliothèque.\nAppuyez sur r pour analyser.", NoLibraryMatches: "Aucun élément ne correspond.\nAppuyez sur Échap pour effacer le filtre.", LibraryEmpty: "La bibliothèque est vide.\nAppuyez sur r pour réanalyser.", EmptyScope: "Ce périmètre ne contient aucune piste.\nChoisissez une autre entrée.", EmptyAlbum: "Aucune piste dans %s / %s.\nChoisissez une autre entrée.", EmptyArtist: "Aucune piste de %s.\nChoisissez une autre entrée.", NoTrackMatches: "Aucune piste ne correspond à %q.\nAppuyez sur Échap pour effacer le filtre.", NoMusicFound: "Aucune musique trouvée.\nVérifiez music_dir, puis appuyez sur r.", EmptyQueue: "La file d’attente est vide.\nLancez une piste depuis Pistes.", TerminalTooSmall: "galdr nécessite au moins %dx%d — dimensions actuelles : %dx%d", SearchPlaceholder: "rechercher…", ResultsOne: "%d/%d résultat", ResultsOther: "%d/%d résultats", DurationsProgress: "Durées %d/%d", DurationsSummaryOne: "Durées %d/%d · %d indisponible", DurationsSummaryOther: "Durées %d/%d · %d indisponibles", Volume: "Vol", Mute: "Muet", Shuffle: "Aléatoire", Repeat: "Répétition", On: "activé", Off: "désactivé", All: "tout", One: "une", ErrorPrefix: "erreur :", ScopeAll: "Périmètre : toutes les pistes", ScopeNamed: "Périmètre : %s", FilterContext: "%s  ·  Filtre : %q (%d/%d)", FilterBadge: "[filtre : %s %d/%d]", MuteBadge: "[muet]", ShuffleBadge: "[aléatoire]", RepeatBadge: "[répétition : %s]", QueueSelected: "sél", QueueNow: "act",
	StatusLibraryScanFailed: "Échec de l’analyse de la bibliothèque", StatusLoadedOne: "%d piste chargée", StatusLoadedOther: "%d pistes chargées", StatusRescanFailed: "Échec de la réanalyse", StatusRescannedOne: "Réanalyse : %d piste", StatusRescannedOther: "Réanalyse : %d pistes", StatusScopeAll: "Périmètre : toutes les pistes", StatusScopeEmpty: "Périmètre : %s/%s (vide)", StatusScopeAlbum: "Périmètre : %s/%s", StatusScopeArtist: "Périmètre : %s", StatusMovedUp: "Déplacé vers le haut", StatusMovedDown: "Déplacé vers le bas", StatusRemovedQueue: "Retiré de la file d’attente", StatusQueueCleared: "File d’attente vidée", StatusFilterCleared: "Filtre effacé", StatusFilter: "Filtre : %s (%d/%d)", StatusVolume: "Volume : %d%%", StatusNoVisibleTracks: "Aucune piste visible à lire", StatusStopped: "Arrêté", StatusEndQueue: "Fin de la file d’attente", StatusFailedAdvance: "Impossible d’avancer", StatusPlaying: "Lecture : %s", StatusShuffleOn: "Lecture aléatoire activée", StatusShuffleOff: "Lecture aléatoire désactivée", StatusRepeatAll: "Répétition : tout", StatusRepeatOne: "Répétition : une", StatusRepeatOff: "Répétition : désactivée", StatusMuted: "Son coupé", StatusUnmuted: "Son rétabli (%d%%)", StatusMutedVolume: "Son coupé (volume : %d%%)", StatusFailedLoad: "Échec du chargement de la piste", StatusFailedStart: "Échec du démarrage de la lecture", StatusFailedPrepare: "Échec de la préparation de la piste suivante", StatusFailedDecode: "Échec du décodage de la piste", StatusFailedStop: "Échec de l’arrêt de la lecture", StatusPaused: "En pause", StatusResumed: "Lecture reprise",
	StatusAddedQueue: "Ajouté à la file : %s", StatusPlayNext: "À suivre : %s", StatusPlaylistListFailed: "Impossible de lister les playlists", StatusPlaylistSaveFailed: "Impossible d’enregistrer la playlist", StatusPlaylistInvalidName: "Nom de playlist invalide", StatusPlaylistLoadFailed: "Impossible de charger la playlist", StatusPlaylistEmptyQueue: "La file d’attente est vide", StatusPlaylistSaved: "%s enregistrée (%d pistes)", StatusPlaylistLoaded: "%s chargée (%d pistes)", StatusPlaylistLoadedSkipped: "%s chargée (%d pistes, %d ignorées)", StatusPlaylistTrackAdded: "%s ajoutée à %s", StatusPlaylistTracksAdded: "%d pistes ajoutées à %s", StatusPlaylistCreatedWithTrack: "%s créée et %s ajoutée", StatusPlaylistCreatedWithTracks: "%s créée avec %d pistes", StatusPlaylistDestinationMissing: "La playlist n’est plus disponible", StatusPlaylistTrackMissing: "La piste n’est plus dans la playlist", StatusPlaylistTrackRemoved: "%s retirée de %s", StatusPlaylistWriteFailed: "Impossible de mettre à jour la playlist",
	ShortcutLibrary: "j/k déplacer  h/l fermer/ouvrir  entrée choisir  A ajouter à une playlist  r réanalyser", ShortcutPlaylists: "j/k déplacer  entrée charger  S enregistrer", ShortcutTracks: "j/k déplacer  entrée lire  a ajouter  A ajouter à une playlist  N à suivre", ShortcutPlaylistTracks: "j/k déplacer  entrée lire  a ajouter  A ajouter à une playlist  N à suivre  d retirer", ShortcutQueue: "j/k déplacer  K/J réordonner  d retirer  c vider  entrée lire", ShortcutGlobal: "tab focus  [/] source  P playlists  / rechercher  ? aide  q quitter", HelpTitle: "Raccourcis", HelpNavigation: "Navigation", HelpPlayback: "Lecture", HelpLibrarySearch: "Bibliothèque et recherche", HelpQueue: "File d’attente", HelpApplication: "Application",
	DiagLoadConfig: "chargement de la configuration", DiagInitAudio: "initialisation audio", DiagLoadState: "impossible de charger l’état :", DiagDurationUnavailable: "analyse des durées indisponible :", DiagMPRISLost: "connexion MPRIS perdue :", DiagMPRISUnavailable: "MPRIS indisponible :", DiagMPRISStop: "impossible d’arrêter MPRIS :", DiagTUI: "interface", DiagSaveState: "impossible d’enregistrer l’état :",
})

var spanish = translated(english, map[Key]string{
	Library: "Biblioteca", Tracks: "Pistas", Queue: "Cola", NowPlaying: "En reproducción", Stopped: "Detenido", Playing: "Reproduciendo", Paused: "En pausa", NothingPlaying: "Nada en reproducción", UnknownArtist: "Artista desconocido", SearchPlaceholder: "buscar…", ResultsOne: "%d/%d resultado", ResultsOther: "%d/%d resultados", DurationsProgress: "Duraciones %d/%d", DurationsSummaryOne: "Duraciones %d/%d · %d no disponible", DurationsSummaryOther: "Duraciones %d/%d · %d no disponibles", Volume: "Vol", Mute: "Silencio", Shuffle: "Aleatorio", Repeat: "Repetición", On: "sí", Off: "no", All: "todo", One: "una", ErrorPrefix: "error:", ScopeAll: "Ámbito: todas las pistas", ScopeNamed: "Ámbito: %s", QueueSelected: "sel", QueueNow: "act", EmptyQueue: "La cola está vacía.\nReproduce una pista desde Pistas.", TerminalTooSmall: "galdr necesita al menos %dx%d — tienes %dx%d", StatusLoadedOne: "%d pista cargada", StatusLoadedOther: "%d pistas cargadas", StatusRescannedOne: "Reanalizada: %d pista", StatusRescannedOther: "Reanalizadas: %d pistas", StatusPlaying: "Reproduciendo: %s", StatusStopped: "Detenido", StatusPaused: "En pausa", StatusResumed: "Reanudado", StatusMuted: "Silenciado", StatusUnmuted: "Sonido activado (%d%%)", StatusVolume: "Volumen: %d%%", StatusEndQueue: "Fin de la cola", StatusShuffleOn: "Aleatorio activado", StatusShuffleOff: "Aleatorio desactivado", StatusRepeatAll: "Repetición: todo", StatusRepeatOne: "Repetición: una", StatusRepeatOff: "Repetición: no", HelpTitle: "Atajos", HelpNavigation: "Navegación", HelpPlayback: "Reproducción", HelpLibrarySearch: "Biblioteca y búsqueda", HelpQueue: "Cola",
})

var german = translated(english, map[Key]string{
	Library: "Bibliothek", Tracks: "Titel", Queue: "Warteschlange", NowPlaying: "Aktuelle Wiedergabe", Stopped: "Gestoppt", Playing: "Wiedergabe", Paused: "Pausiert", NothingPlaying: "Keine Wiedergabe", UnknownArtist: "Unbekannter Interpret", SearchPlaceholder: "suchen…", ResultsOne: "%d/%d Ergebnis", ResultsOther: "%d/%d Ergebnisse", DurationsProgress: "Laufzeiten %d/%d", DurationsSummaryOne: "Laufzeiten %d/%d · %d nicht verfügbar", DurationsSummaryOther: "Laufzeiten %d/%d · %d nicht verfügbar", Volume: "Lautst.", Mute: "Stumm", Shuffle: "Zufall", Repeat: "Wiederholung", On: "an", Off: "aus", All: "alle", One: "einen", ErrorPrefix: "Fehler:", ScopeAll: "Bereich: alle Titel", ScopeNamed: "Bereich: %s", QueueSelected: "aus", QueueNow: "jet", EmptyQueue: "Die Warteschlange ist leer.\nEinen Titel aus Titel abspielen.", TerminalTooSmall: "galdr benötigt mindestens %dx%d — vorhanden sind %dx%d", StatusLoadedOne: "%d Titel geladen", StatusLoadedOther: "%d Titel geladen", StatusRescannedOne: "Neu eingelesen: %d Titel", StatusRescannedOther: "Neu eingelesen: %d Titel", StatusPlaying: "Wiedergabe: %s", StatusStopped: "Gestoppt", StatusPaused: "Pausiert", StatusResumed: "Fortgesetzt", StatusMuted: "Stummgeschaltet", StatusUnmuted: "Ton an (%d%%)", StatusVolume: "Lautstärke: %d%%", StatusEndQueue: "Ende der Warteschlange", StatusShuffleOn: "Zufallswiedergabe an", StatusShuffleOff: "Zufallswiedergabe aus", StatusRepeatAll: "Wiederholung: alle", StatusRepeatOne: "Wiederholung: einen", StatusRepeatOff: "Wiederholung: aus", HelpTitle: "Tastenkürzel", HelpNavigation: "Navigation", HelpPlayback: "Wiedergabe", HelpLibrarySearch: "Bibliothek und Suche", HelpQueue: "Warteschlange",
})

func init() {
	override(french, map[Key]string{
		UnavailableOne: "%d indisponible", UnavailableOther: "%d indisponibles",
		HelpNavMove: "j / k, ↑ / ↓    déplacer la sélection", HelpNavOpen: "h / l, ← / →    chercher ou ouvrir / fermer", HelpNavPanel: "tab / maj+tab    panneau suivant / précédent", HelpNavChoose: "1 / 2 / 3        Bibliothèque / Pistes / File", HelpNavSelect: "entrée           choisir ou lire", HelpNavSeek: "début / fin      aller au début / à la fin", HelpPlayPause: "espace           lire / pause", HelpStop: "x                arrêter", HelpNextPrev: "n / p            suivant / précédent", HelpVolume: "+ / -            augmenter / baisser le volume", HelpMute: "m                couper le son", HelpShuffleRepeat: "s / R            aléatoire / répétition", HelpRescan: "r                réanalyser la bibliothèque", HelpSearch: "/                rechercher", HelpClearFilter: "Échap / C-l      fermer / effacer le filtre", HelpQueueUp: "K / maj+↑        monter l’élément", HelpQueueDown: "J / maj+↓        descendre l’élément", HelpQueueRemove: "d / c            retirer / vider", HelpQueueAdd: "a                ajouter la piste sélectionnée", HelpPlayNext: "N                lire la sélection ensuite", HelpAddPlaylist: "A                ajouter une piste, un artiste ou un album à une playlist", HelpPlaylistRemove: "d                retirer l’occurrence sélectionnée de la playlist", HelpPlaylists: "P                ouvrir les playlists", HelpClose: "? / échap        fermer l’aide", HelpQuit: "q / ctrl+c       quitter",
	})
	override(spanish, map[Key]string{
		EmptyLibrary: "No hay biblioteca.\nPulsa r para analizar.", NoLibraryMatches: "Ningún elemento coincide.\nPulsa Esc para borrar el filtro.", LibraryEmpty: "La biblioteca está vacía.\nPulsa r para volver a analizar.", EmptyScope: "Este ámbito no contiene pistas.\nElige otra entrada de la Biblioteca.", EmptyAlbum: "No hay pistas en %s / %s.\nElige otra entrada de la Biblioteca.", EmptyArtist: "No hay pistas de %s.\nElige otra entrada de la Biblioteca.", NoTrackMatches: "Ninguna pista coincide con %q.\nPulsa Esc para borrar el filtro.", NoMusicFound: "No se encontró música.\nComprueba music_dir y pulsa r.",
		UnavailableOne: "%d no disponible", UnavailableOther: "%d no disponibles", FilterContext: "%s  ·  Filtro: %q (%d/%d)", FilterBadge: "[filtro: %s %d/%d]", MuteBadge: "[silencio]", ShuffleBadge: "[aleatorio]", RepeatBadge: "[repetición: %s]",
		StatusLibraryScanFailed: "Error al analizar la biblioteca", StatusRescanFailed: "Error al volver a analizar", StatusScopeAll: "Ámbito: todas las pistas", StatusScopeEmpty: "Ámbito: %s/%s (vacío)", StatusScopeAlbum: "Ámbito: %s/%s", StatusScopeArtist: "Ámbito: %s", StatusMovedUp: "Movida hacia arriba", StatusMovedDown: "Movida hacia abajo", StatusRemovedQueue: "Eliminada de la cola", StatusQueueCleared: "Cola vaciada", StatusFilterCleared: "Filtro borrado", StatusFilter: "Filtro: %s (%d/%d)", StatusNoVisibleTracks: "No hay pistas visibles para reproducir", StatusFailedAdvance: "No se pudo avanzar", StatusMutedVolume: "Silenciado (volumen: %d%%)", StatusFailedLoad: "No se pudo cargar la pista", StatusFailedStart: "No se pudo iniciar la reproducción", StatusFailedPrepare: "No se pudo preparar la pista siguiente", StatusFailedDecode: "No se pudo decodificar la pista", StatusFailedStop: "No se pudo detener la reproducción",
		ShortcutLibrary: "j/k mover  h/l cerrar/abrir  intro elegir  A añadir a lista  r analizar", ShortcutTracks: "j/k mover  intro reproducir  a añadir  A añadir a lista  N siguiente", ShortcutPlaylistTracks: "j/k mover  intro reproducir  a añadir  A añadir a lista  N siguiente  d quitar", ShortcutQueue: "j/k mover  K/J reordenar  d quitar  c vaciar  intro reproducir", ShortcutGlobal: "tab foco  1/2/3 paneles  / buscar  ? ayuda  q salir", HelpApplication: "Aplicación", HelpAddPlaylist: "A                añadir pista, artista o álbum a una lista", HelpPlaylistRemove: "d                quitar la aparición seleccionada de la lista",
		HelpNavMove: "j / k, ↑ / ↓    mover selección", HelpNavOpen: "h / l, ← / →    buscar o abrir / cerrar", HelpNavPanel: "tab / mayús+tab  panel siguiente / anterior", HelpNavChoose: "1 / 2 / 3        Biblioteca / Pistas / Cola", HelpNavSelect: "intro            seleccionar o reproducir", HelpNavSeek: "inicio / fin     ir al inicio / final", HelpPlayPause: "espacio          reproducir / pausa", HelpStop: "x                detener", HelpNextPrev: "n / p            siguiente / anterior", HelpVolume: "+ / -            subir / bajar volumen", HelpMute: "m                silenciar", HelpShuffleRepeat: "s / R            aleatorio / repetición", HelpRescan: "r                analizar biblioteca", HelpSearch: "/                buscar", HelpClearFilter: "Esc / C-l        cerrar / borrar filtro", HelpQueueUp: "K / mayús+↑      subir elemento", HelpQueueDown: "J / mayús+↓      bajar elemento", HelpQueueRemove: "d / c            quitar / vaciar", HelpClose: "? / esc          cerrar ayuda", HelpQuit: "q / ctrl+c       salir",
		DiagLoadConfig: "cargar configuración", DiagInitAudio: "inicializar audio", DiagLoadState: "no se pudo cargar el estado:", DiagDurationUnavailable: "análisis de duraciones no disponible:", DiagMPRISLost: "conexión MPRIS perdida:", DiagMPRISUnavailable: "MPRIS no disponible:", DiagMPRISStop: "no se pudo detener MPRIS:", DiagTUI: "interfaz", DiagSaveState: "no se pudo guardar el estado:",
	})
	override(german, map[Key]string{
		EmptyLibrary: "Keine Bibliothek.\nZum Einlesen r drücken.", NoLibraryMatches: "Keine passenden Einträge.\nZum Löschen des Filters Esc drücken.", LibraryEmpty: "Die Bibliothek ist leer.\nZum erneuten Einlesen r drücken.", EmptyScope: "Dieser Bereich enthält keine Titel.\nEinen anderen Bibliothekseintrag wählen.", EmptyAlbum: "Keine Titel in %s / %s.\nEinen anderen Bibliothekseintrag wählen.", EmptyArtist: "Keine Titel von %s.\nEinen anderen Bibliothekseintrag wählen.", NoTrackMatches: "Keine Titel passen zu %q.\nZum Löschen des Filters Esc drücken.", NoMusicFound: "Keine Musik gefunden.\nmusic_dir prüfen und r drücken.",
		UnavailableOne: "%d nicht verfügbar", UnavailableOther: "%d nicht verfügbar", FilterContext: "%s  ·  Filter: %q (%d/%d)", FilterBadge: "[Filter: %s %d/%d]", MuteBadge: "[stumm]", ShuffleBadge: "[Zufall]", RepeatBadge: "[Wiederholung: %s]",
		StatusLibraryScanFailed: "Einlesen der Bibliothek fehlgeschlagen", StatusRescanFailed: "Erneutes Einlesen fehlgeschlagen", StatusScopeAll: "Bereich: alle Titel", StatusScopeEmpty: "Bereich: %s/%s (leer)", StatusScopeAlbum: "Bereich: %s/%s", StatusScopeArtist: "Bereich: %s", StatusMovedUp: "Nach oben verschoben", StatusMovedDown: "Nach unten verschoben", StatusRemovedQueue: "Aus der Warteschlange entfernt", StatusQueueCleared: "Warteschlange geleert", StatusFilterCleared: "Filter gelöscht", StatusFilter: "Filter: %s (%d/%d)", StatusNoVisibleTracks: "Keine sichtbaren Titel zum Abspielen", StatusFailedAdvance: "Wechsel zum nächsten Titel fehlgeschlagen", StatusMutedVolume: "Stumm (Lautstärke: %d%%)", StatusFailedLoad: "Titel konnte nicht geladen werden", StatusFailedStart: "Wiedergabe konnte nicht gestartet werden", StatusFailedPrepare: "Nächster Titel konnte nicht vorbereitet werden", StatusFailedDecode: "Titel konnte nicht dekodiert werden", StatusFailedStop: "Wiedergabe konnte nicht gestoppt werden",
		ShortcutLibrary: "j/k bewegen  h/l schließen/öffnen  Eingabe wählen  A zu Playlist  r einlesen", ShortcutTracks: "j/k bewegen  Eingabe spielen  a hinzufügen  A zu Playlist  N als Nächstes", ShortcutPlaylistTracks: "j/k bewegen  Eingabe spielen  a hinzufügen  A zu Playlist  N als Nächstes  d entfernen", ShortcutQueue: "j/k bewegen  K/J sortieren  d entfernen  c leeren  Eingabe abspielen", ShortcutGlobal: "Tab Fokus  1/2/3 Bereiche  / suchen  ? Hilfe  q beenden", HelpApplication: "Anwendung", HelpAddPlaylist: "A                Titel, Interpret oder Album zu Playlist hinzufügen", HelpPlaylistRemove: "d                ausgewählten Playlist-Eintrag entfernen",
		HelpNavMove: "j / k, ↑ / ↓    Auswahl bewegen", HelpNavOpen: "h / l, ← / →    suchen oder öffnen / schließen", HelpNavPanel: "Tab / Umsch+Tab  nächster / vorheriger Bereich", HelpNavChoose: "1 / 2 / 3        Bibliothek / Titel / Warteschlange", HelpNavSelect: "Eingabe          wählen oder abspielen", HelpNavSeek: "Pos1 / Ende      zum Anfang / Ende springen", HelpPlayPause: "Leertaste        abspielen / pausieren", HelpStop: "x                stoppen", HelpNextPrev: "n / p            nächster / vorheriger Titel", HelpVolume: "+ / -            Lautstärke erhöhen / senken", HelpMute: "m                stummschalten", HelpShuffleRepeat: "s / R            Zufall / Wiederholung", HelpRescan: "r                Bibliothek neu einlesen", HelpSearch: "/                suchen", HelpClearFilter: "Esc / C-l        schließen / Filter löschen", HelpQueueUp: "K / Umsch+↑      Eintrag nach oben", HelpQueueDown: "J / Umsch+↓      Eintrag nach unten", HelpQueueRemove: "d / c            entfernen / leeren", HelpClose: "? / Esc          Hilfe schließen", HelpQuit: "q / Strg+c       beenden",
		DiagLoadConfig: "Konfiguration laden", DiagInitAudio: "Audio initialisieren", DiagLoadState: "Status konnte nicht geladen werden:", DiagDurationUnavailable: "Laufzeitanalyse nicht verfügbar:", DiagMPRISLost: "MPRIS-Verbindung verloren:", DiagMPRISUnavailable: "MPRIS nicht verfügbar:", DiagMPRISStop: "MPRIS konnte nicht beendet werden:", DiagTUI: "Oberfläche", DiagSaveState: "Status konnte nicht gespeichert werden:",
	})
}

func override(catalogue map[Key]string, translations map[Key]string) {
	for key, value := range translations {
		catalogue[key] = value
	}
}

func translated(base map[Key]string, overrides map[Key]string) map[Key]string {
	out := make(map[Key]string, len(base))
	for key, value := range base {
		out[key] = value
	}
	for key, value := range overrides {
		out[key] = value
	}
	return out
}
